name: Despliegue EKS en AWS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CLUSTER: gamecatalog-cluster
    steps:
      #git clone...
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configurar las credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: ${{env.AWS_REGION}}
      
      - name: Loguear con ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Obtener el AWS ACCOUNT ID
        run: |
          echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Definir las URL de los ECR
        run: |
          echo "BACKEND_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend_gamecatalog" >> $GITHUB_ENV
          echo "FRONTEND_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend_gamecatalog" >> $GITHUB_ENV

      - name: Construir el backend
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $BACKEND_ECR:${GITHUB_SHA} \
            ./backend \
            --load
      - name: Push del backend
        run: |
          docker push $BACKEND_ECR:${GITHUB_SHA}
      
      - name: Construir el frontend
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $FRONTEND_ECR:${GITHUB_SHA} \
            ./frontend \
            --load
      - name: Push del frontend
        run: |
          docker push $FRONTEND_ECR:${GITHUB_SHA}
      
      - name: Instalar kubernet
        uses: azure/setup-kubectl@v4
      
      - name: Conectar el EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER
      - name: Aplicar kubernets
        run: |
          kubectl apply -f infra/k8s/
      
      - name: Actualizar nombre de la imagen del backend.yml
        run: |
          kubectl set image deployment/backend \
          backend=$BACKEND_ECR:${GITHUB_SHA}
      - name: Actualizar nombre de la imagen del frontend.yml
        run: |
          kubectl set image deployment/frontend \
          frontend=$FRONTEND_ECR:${GITHUB_SHA}
      
      - name: Esperar la recarga del backend
        run: |
          kubectl rollout status deployment/backend
      - name: Esperar la recarga del frontend
        run: |
          kubectl rollout status deployment/frontend

      - name: Obtener le IP del frontend
        run: |
          kubectl get service frontend -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
